# 
# docker stack deploy -c geoos-dev.yml geoos
# 
version: '3.6'

services:
  db:
    image: mongo:4.4.1-bionic
    environment:
      #MONGO_INITDB_ROOT_USERNAME: geoos-admin
      #MONGO_INITDB_ROOT_PASSWORD: geoos-password
      LOG_LEVEL: debug
    volumes:
      - ./mongo-data:/data/db

  portal:
    image: guilewasser/oilportal:latest
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 9234:9234/tcp # nodemon debugger
      - 8090:8090/tcp
    working_dir: /usr/src/app
    environment:
      MONGO_URL: "mongodb://db:27017"
      MONGO_DATABASE: geoos
      LOG_LEVEL: debug
    volumes:
      - ./portal:/usr/src/app
      - ./config:/home/config
      - ./data:/home/data
    command: "npm run-script debug"

  geoserver:
    image: guilewasser/pglang:latest
    #image: docker.homejota.net/geoos/gdal-node16-nco-cdo
    #image: docker.homejota.net/geoos/gdal-node14-arm
    #image: docker.homejota.net/geoos/gdal-node14
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 9231:9231/tcp # nodemon debugger
      - 8080:8080 # web server
    working_dir: /usr/src/app
    environment:
      LOG_LEVEL: debug
    volumes:
      - ./geoserver:/usr/src/app
      - ./data:/home/data
      - ./config:/home/config
      - ./log:/home/log
      - ./www:/home/www
    command: "npm run-script debug"

  zrepo:
    image: node:14-alpine
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 9235:9235/tcp # nodemon debugger
      - 8096:8096/tcp
    working_dir: /usr/src/app
    environment:
      MONGO_URL: "mongodb://db:27017"
      MONGO_DATABASE: zrepo
      LOG_LEVEL: debug
    volumes:
      - ./z-repo:/usr/src/app
      - ./config:/home/config
      - ./log:/home/log
      - ./data:/home/data
    command: "npm run-script debug"
